export default [
  {
    id: "1",
    price: "59.99€",
    rating: "89%",
    editor: "Paradox",
    title: "Endless space 2",
    style: "4x",
    release: "19/03/2019",
  },
  {
    id: "2",
    price: "59.99€",
    rating: "89%",
    editor: "Paradox",
    title: "Crusader Kings 3",
    style: "FPS",
    release: "19/03/2021",
  },
  {
    id: "3",
    price: "59.99€",
    rating: "89%",
    editor: "Paradox",
    title: "Crusader Kings 3",
    style: "FPS",
    release: "19/03/2021",
  },
  {
    id: "4",
    price: "59.99€",
    rating: "89%",
    editor: "Paradox",
    title: "Endless space 2",
    style: "4x",
    release: "19/03/2019",
  },
  {
    id: "5",
    price: "59.99€",
    rating: "89%",
    editor: "Paradox",
    title: "Crusader Kings 3",
    style: "FPS",
    release: "19/03/2021",
  },
  {
    id: "6",
    price: "59.99€",
    rating: "89%",
    editor: "Paradox",
    title: "Crusader Kings 3",
    style: "FPS",
    release: "19/03/2021",
  },
  {
    id: "7",
    price: "59.99€",
    rating: "89%",
    editor: "Paradox",
    title: "Crusader Kings 3",
    style: "FPS",
    release: "19/03/2021",
  },
];
